name: scanneru
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  shared_preferences: ^2.0.7
  permission_handler: ^8.1.4+2
  share: ^2.0.4
  file_picker: ^4.0.0
  pdf: ^3.4.2
  carousel_slider: ^4.0.0
  path_provider: ^2.0.2
  flutter_native_splash: ^1.2.1
  native_pdf_renderer: ^3.1.0
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

